// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS6QDkw9jZxb_TXcZUv_D4NB8qcPF5SLY',
    appId: '1:105378934751:web:28897b3d83884e6c411e6a',
    messagingSenderId: '105378934751',
    projectId: 'heroic-tide-428421-q7',
    authDomain: 'heroic-tide-428421-q7.firebaseapp.com',
    databaseURL: 'https://heroic-tide-428421-q7-default-rtdb.firebaseio.com',
    storageBucket: 'heroic-tide-428421-q7.firebasestorage.app',
    measurementId: 'G-Q4JVFC4LMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP-wwQVYLSKcc_2HM2jpwz66J3UoTjfYc',
    appId: '1:485820050685:android:51977b91fe3344bff5a294',
    messagingSenderId: '485820050685',
    projectId: 'brightacts-frontend',
    storageBucket: 'brightacts-frontend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWkBIodUPOhKe-QyUqJoG3q1DKzhybB0',
    appId: '1:485820050685:ios:fde1cd45bca84989f5a294',
    messagingSenderId: '485820050685',
    projectId: 'brightacts-frontend',
    storageBucket: 'brightacts-frontend.firebasestorage.app',
    iosBundleId: 'com.example.brightactsFrontendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbWkBIodUPOhKe-QyUqJoG3q1DKzhybB0',
    appId: '1:485820050685:ios:fde1cd45bca84989f5a294',
    messagingSenderId: '485820050685',
    projectId: 'brightacts-frontend',
    storageBucket: 'brightacts-frontend.firebasestorage.app',
    iosBundleId: 'com.example.brightactsFrontendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxGoFjc0I-BXyZnOviJBuhc48JpdH4NUg',
    appId: '1:485820050685:web:70b3bac5cf8e8f6ff5a294',
    messagingSenderId: '485820050685',
    projectId: 'brightacts-frontend',
    authDomain: 'brightacts-frontend.firebaseapp.com',
    storageBucket: 'brightacts-frontend.firebasestorage.app',
    measurementId: 'G-Q0GXVST7B5',
  );
}