name: Flutter Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6' # or your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web --release

      - name: Verify build/web
        run: ls -la build/web

      - name: Setup Firebase CLI
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # Github token for Actions
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: brightacts-frontend-50f58
